name: Web DoctorDocker Compose CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container Stack
        id: build-container-stack
        run: docker-compose up -d